### ISSUE TITLE
500 error loading dashboard

### ISSUE THREAD

**Issue by ambs** [eXist-db/docker-existdb#71]
Hi.

Trying latest tag. Copied all xml files from the config folder, created a docker-compose up, and I am getting these errors.

Any help is welcome.

``````
HTTP ERROR 500

Problem accessing /exist/apps/dashboard/. Reason:

    Server Error

Caused by:

javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:371)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	... 16 more
Caused by: org.exist.xquery.XPathException: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:294)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:261)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:94)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:55)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:51)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11190)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7776)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3082)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:420)
	at org.exist.xquery.parser.XQueryTreeParser.functionDecl(XQueryTreeParser.java:6201)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5333)
	at org.exist.xquery.parser.XQueryTreeParser.libraryModule(XQueryTreeParser.java:4030)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3861)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2484)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2425)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2378)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6312)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5340)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4042)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:243)
	... 34 more

Caused by:

javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:371)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.exist.xquery.XPathException: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:294)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:261)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:94)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:55)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:51)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11190)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7776)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3082)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:420)
	at org.exist.xquery.parser.XQueryTreeParser.functionDecl(XQueryTreeParser.java:6201)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5333)
	at org.exist.xquery.parser.XQueryTreeParser.libraryModule(XQueryTreeParser.java:4030)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3861)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2484)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2425)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2378)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6312)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5340)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4042)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:243)
	... 34 more

Caused by:

org.exist.xquery.XPathException: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:294)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:261)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:94)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:55)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:51)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11190)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7776)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3082)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:420)
	at org.exist.xquery.parser.XQueryTreeParser.functionDecl(XQueryTreeParser.java:6201)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5333)
	at org.exist.xquery.parser.XQueryTreeParser.libraryModule(XQueryTreeParser.java:4030)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3861)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2484)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2425)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2378)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6312)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5340)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4042)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:243)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

Powered by Jetty:// 9.4.14.v20181114 
``````

**Comment by duncdrum** [comment]
Yes this is a known issue unrelated to docker. With recent changes on the develop branch all Dashboard apps are broken. 

work on fix is ongoing, so the app on `:latest` will start working again soon, in the meantime i would suggest using a tagged version either `:release` or one of the Release Candidates, e.g. `5.0.0-RC6`


see eXist-db/exist#2626 to track progress of the fixes

see eXist-db/dashboard#83 for the underlying issue

**Comment by ambs** [comment]
Great, thanks for letting me know. I had the same issue with the snapshot of version 5, and that's why I tested this. Will test RC6, then.

**Comment by duncdrum** [comment]
after a small hickup, with dashboard 2.0.1 being falsely installed on `release` all tags are working again. Please open a new issue if you encounter problems after pulling a fresh version of the images.
